### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by corsacca** [thecodezone/dt-home#131]
Running into this error when running `composer install`.

https://github.com/thecodezone/dt-home/blob/c880e26eb3718d6b60e63aefb454c79d0c12362b/bin/setup-scoper.sh#L1

bin/setup-scoper.sh: line 1: /Users/[user]/.bashrc: No such file or directory

**Comment by incraigulous** [comment]
@corsacca , are you on windows?

**Comment by corsacca** [comment]
I'm on mac.
I probably could just create the .bashrc file.

**Comment by incraigulous** [comment]
@corsacca , https://github.com/thecodezone/dt-home/commit/7ea6b59434beecbb2319467a6f0547bb7e0e2d19
